# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
  displayName: 'Select the Xamarin SDK version'
  enabled: false

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'src/MiBocata.Client/MiBocata.Client.sln'

- task: XamariniOS@2
  inputs:
    solutionFile: 'src/MiBocata.Client/MiBocata/MiBocata.iOS/MiBocata.iOS.csproj'
    configuration: 'Release'
    buildForSimulator: true
    packageApp: false
