name: CI BUSINNES

on:
  push:
    branches: [ master ]
    paths:
      - 'src/MiBocata.Businnes/**'
      - 'src/Commons/**'    
      - '.github/workflows/businnes-ci.yml'
      - '.github/workflows/template-maui-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/MiBocata.Businnes/**'
      - 'src/Commons/**'    
      - '.github/workflows/businnes-ci.yml'
      - '.github/workflows/template-maui-ci.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-mobile:
    uses: ./.github/workflows/template-maui-ci.yml
    with:
      csproj: src/MiBocata.Businnes/MiBocata.Businnes.csproj