name: CD BUSINNES

on:
  push:
    branches: [ master ]
    paths:
      - 'src/MiBocata.Businnes/**'
      - 'src/Commons/**'    
      - '.github/workflows/businnes-cd.yml'
      - '.github/workflows/template-maui-cd.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/MiBocata.Businnes/**'
      - 'src/Commons/**'    
      - '.github/workflows/businnes-cd.yml'
      - '.github/workflows/template-maui-cd.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-mobile:
    uses: ./.github/workflows/template-maui-cd.yml
    with:
      csproj: src/MiBocata.Businnes/MiBocata.Businnes.csproj
      root_path: src/MiBocata.Businnes/
      encrypted_keystore_path: android-keystore-test.jks.gpg
      keystore_path: android-keystore-test.keystore
    secrets:  
      android_keystore_gpg_pass: ${{secrets.ANDROID_KEYSTORE_GPG_PASSWORD}}
      android_signing_store_pass: ${{secrets.ANDROID_SIGNING_STORE_PASS}}
      android_signing_key_alias: ${{secrets.ANDROID_SIGNING_KEY_ALIAS}}
      android_signing_key_pass: ${{secrets.ANDROID_SIGNING_KEY_PASS}}
