name: CI CLIENT

on:
  push:
    branches: [ master ]
    paths:
      - 'src/MiBocata.Client/**'
      - 'src/Commons/**'
      - '.github/workflows/client-ci.yml'
      - '.github/workflows/template-maui-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/MiBocata.Client/**'
      - 'src/Commons/**'      
      - '.github/workflows/client-ci.yml'
      - '.github/workflows/template-maui-ci.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-mobile:
    uses: ./.github/workflows/template-maui-ci.yml
    with:
      csproj: src/MiBocata.Client/MiBocata.csproj
