on:
  workflow_call:
    inputs:
      csproj:
        required: true
        type: string

jobs:
  build-mobile:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
          include-prerelease: true

      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'     

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui

      - name: Build MAUI Mobile app
        shell: pwsh
        run: |
          dotnet build ${{inputs.csproj}} -f net8.0-android -bl:mobile.binlog

      - name: Archive build log
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: '*.binlog'
